export enum ENDPOINT {
  LOGIN = "/merchant/auth/login",
  BRAND_MOTOR = "/master-data/motor-brand",
  LIST_PRODUCT = "/products",
  DETAIL_PRODUCT = "/products/detail",
  PROFILE = "/merchant/me ",
  LIST_TRANSACTIONS = "/merchant/transactions/history",
  SUBMIT_TRANSACTIONS = "/transactions/submit",
  UPLOAD_BRAND = "/merchant/master-data/brand-motor/add",
  TIRE_TYPE = "/master-data/tire-type",
  UPLOAD_PRODUCT = "/merchant/products/add",
  TIRE_SIZE = "/master-data/tire-size",
  DELETE_PRODUCT = "/merchant/products/delete",
  UPDATE_STATUS_TRANSACTIONS = "/merchant/transactions/update-status",
  DETAIL_TRANSACTION = "/merchant/transactions/detail",
  TIRE_BRAND = "/master-data/tire-brand",
}
